{% set name = "pygeometa" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeometa-{{ version }}.tar.gz
  sha256: c5d42a3602a9515d4cbc6128f692fb13d33e5d6022015dd6530fee1fa9ad90ab

build:
  number: 0
  noarch: python
  entry_points:
    - pygeometa=pygeometa:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click
    - jinja2
    - jsonschema
    - lxml
    - owslib
    - pyyaml


test:
  imports:
    - pygeometa
    - pygeometa.schemas
  commands:
    - pip check
    - pygeometa --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/geopython/pygeometa
  license: MIT
  license_file: LICENSE.md
  summary: pygeometa is a Python package to generate metadata for geospatial datasets
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
